language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r AWSWebProject *
  - mkdir -p deploy
  - mv AWSWebProject.zip deploy/AWSWebProject.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: awswebprojectdeployjar
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: awswebprojectdeployjar
    key: AWSWebProject.zip
    application: AWSWebProject
    deployment_group: AWSWebProject-group
    region: ap-northeast-2
    wait-until-deployed: true


#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - energizermj104@gmail.com