language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#deploy에 전체 소스 zip으로 묶어서 S3로 전송
#before_deploy:
#  - zip -r AWSWebProject *
#  - mkdir -p deploy
#  - mv AWSWebProject.zip deploy/AWSWebProject.zip

#배포에 필요한 Jar, appspec.yml, 배포를위한 스크립트 (deploy.sh)만 S3로 전송
before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/AWSWebProject.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: awswebprojectdeployjar
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: awswebprojectdeployjar
    key: AWSWebProject.zip
    application: AWSWebProject
    deployment_group: AWSWebProject-group
    region: ap-northeast-2
    wait-until-deployed: true


#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - energizermj104@gmail.com